inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.4
  Include:
    - 'app/**/*'
    - 'spec/**/*'
    - 'db/migrate/*'
    - 'lib/**/*'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec

########## Lint cops

Lint/EmptyFile:
  Enabled: false

########## Style cops

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: false
