inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.4
  Include:
    - 'app/**/*'
    - 'spec/**/*'
    - 'db/migrate/*'
    - 'lib/**/*'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec

########## Layout cops

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Max: 100

########## Lint cops

Lint/EmptyFile:
  Enabled: false

########## Metrics cops

Metrics/MethodLength:
  Max: 15

########## Style cops

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: false

########## Rspec cops
RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/ExampleLength:
  Max: 15
